name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag darkryder16/playlist_downloader:$IMAGE_TAG
    - name: Push the Docker image to hub
      run: docker push darkryder16/playlist_downloader:$IMAGE_TAG
